service: serverless-practice

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    DYNAMODB_TABLE: serverless-practice
    S3_BUCKET_NAME: serverless-practice-data
    SERVICE_NAME: practice
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    USER_ID: ${env:USER_ID}
    CHANNEL_ID: ${env:CHANNEL_ID}
  deploymentBucket:
    name: serverless-practice-service-bucket

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:ap-northeast-2:*:table/serverless-practice

        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: arn:aws:s3:::serverless-practice/*

        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: arn:aws:s3:::serverless-practice

functions:
  ### 게시판 ###
  - ${file(./crud/functions.yml):functions}
  ### 슬랙 ###
  - ${file(./slack/functions.yml):functions}
  ### 로그인 ###
  ### 유저 ###

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap:
      type: linked
    external:
      - '@aws-sdk/*'
